### ISSUE TITLE
idea: show some birthday statistics since the last birthday

### ISSUE THREAD

**Issue by fabiangreffrath** [lamby/installation-birthday#1]
I think it would be cool if i-b could show some "birthday statistics", e.g. 

"Since the last birthday the root filesystem has grown by X files and Y MB, X packages have been installed and Y have been removed, X new users have been added to the system and Y removed."

**Comment by lamby** [comment]
Thank you for the suggestion. However, this would require storing state which not only would complicate a simple program it wouldn't necessary be very reliable. It would also require the package to be installed for over a year, so there isn't much "return" on implementing such a feature. Anyway, thanks again...
